---
- name: Install zookeeper packages
  when: ansible_os_family == 'Debian'
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - zookeeper
    - zookeeperd

- include: upstream_install.yml
  when: ansible_os_family != 'Debian'

- name: Deploy configuration files
  template:
    src: "{{ item }}"
    dest: "{{ zookeeper_config_dir }}/{{ item }}"
  with_items:
    - myid
    - zoo.cfg
    - log4j.properties
  notify: Restart zookeeper

# this is not necessary, just useful to have
- name: Link the zkCli
  file:
    src: "/usr/share/zookeeper/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
  with_items:
    - zkCli.sh
    - zkEnv.sh

- meta: flush_handlers

- name: Start service
  service:
    name: zookeeper
    state: started
    enabled: yes
