---
- name: Create Logstash configuration files.
  template:
    src: "etc/logstash/conf.d/{{ item }}"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 01-beats-input.conf
    - 30-elasticsearch-output.conf
  notify: restart logstash

- name: Create Logstash base filters.
  copy:
    src: "{{ item }}"
    dest: "/etc/logstash/conf.d/{{ item | basename }}"
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - "etc/logstash/conf.d/*"
  notify: restart logstash
