---
- name: Install Packages.
  when: ansible_os_family == 'Debian'
  apt:
    name: logstash
    state: present

- name: Install Packages.
  when: ansible_os_family == 'RedHat'
  yum:
    name: logstash
    state: present

- include: config.yml
- include: ssl.yml
- include: plugins.yml

- meta: flush_handlers

- name: Ensure Logstash is started and enabled on boot.
  service:
    name: logstash
    state: started
    enabled: yes
