- name: Install nginx
  yum:
    name:
      - nginx

# this task doesn't make as much sense with nginx but it means that
# letsencrypt can work the same way across apache and nginx
- name: create document root
  file:
    path: "{{ item.document_root }}"
    state: directory
    owner: "{{ item.document_root_owner | default(omit) }}"
    group: "{{ item.document_root_group | default(omit) }}"
    mode: "{{ item.document_root_mode | default(omit) }}"
  with_items: "{{ nginx_sites }}"
  when: item.document_root is defined

- name: Install sites
  template:
    src: vhost.conf
    dest: "/etc/nginx/conf.d/{{ item.name }}.conf"
    mode: "0644"
  when: item.state | default('present') == 'present'
  with_items: "{{ nginx_sites }}"
  notify: Reload nginx

- name: Remove sites
  file:
    path: "/etc/nginx/conf.d/{{ item.name }}.conf"
    state: absent
  when: item.state | default('present') == 'absent'
  with_items: "{{ nginx_sites }}"

- meta: flush_handlers

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: yes
