dependencies:
  - role: python-app
    name: zuul
    python_app_pipdeps:
      - name: jenkins-job-builder
        version: '1.6.1'
      - name: pyzmq
      - name: ansible
      - name: statsd
    python_app_git_repo: "{{ zuul_git_repo_url }}"
    python_app_git_version: "{{ zuul_git_branch }}"
    python_app_notify: Restart zuul
