dependencies:
  - role: python-app
    name: zuul
    python_app_pipdeps:
      - name: pyzmq
      - name: ansible
      - name: statsd
      - name: git+https://github.com/sigmavirus24/github3.py.git@8e9ca0056b8fed956b66dafb5398757cd8d8bed9#egg=Github3.py
        when: "{{ not zuul_zuul_v3 }}"
    python_app_git_repo: "{{ zuul_git_repo_url }}"
    python_app_git_version: "{{ zuul_git_branch }}"
    python_app_notify: Restart zuul
