---
- name: Create config directories
  file:
    path: "{{ zuul_config_dir }}/config"
    state: directory
    mode: 0755
    owner: zuul
    group: zuul

- name: Create zuul state dir
  file:
    path: "{{ zuul_server_state_dir }}"
    state: directory
    owner: zuul
    group: zuul

- name: Install gearman logging configs
  template:
    src: "etc/zuul/gearman-logging.conf"
    dest: "{{ zuul_config_dir }}/gearman-logging.conf"
    owner: zuul

- name: Install layout.yaml
  template:
    src: etc/zuul/config/layout.yaml
    dest: "{{ zuul_config_dir }}/config/layout.yaml"
    owner: zuul
  notify: Reload zuul-server

- name: install magic functions file
  copy:
    src: etc/zuul/config/bonnyci_functions.py
    dest: "{{ zuul_config_dir }}/config/bonnyci_functions.py"
    owner: zuul
  notify: Reload zuul-server

- name: Create zuul status lib dir
  file:
    path: /opt/source/zuul/etc/status/public_html/lib
    state: directory

- name: Install jquery and jquery-visibility
  get_url:
    url: "{{ item }}"
    dest: /opt/source/zuul/etc/status/public_html/lib
  with_items:
    - https://code.jquery.com/jquery.min.js
    - https://raw.githubusercontent.com/mathiasbynens/jquery-visibility/master/jquery-visibility.js
    - https://raw.githubusercontent.com/prestontimmons/graphitejs/master/jquery.graphite.js

- name: Create bootstrap css dir
  file:
    path: /opt/source/zuul/etc/status/public_html/lib/bootstrap/css
    state: directory

- name: Download bootstrap
  get_url:
    url: https://maxcdn.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css
    dest: /opt/source/zuul/etc/status/public_html/lib/bootstrap/css/bootstrap.min.css

# we don't do this in zuul-base so we can config additional things
- name: Start zuul-server
  service:
    name: zuul-server
    state: started
