dependencies:
  - pip
  - role: tailon
    tailon_ip: 127.0.0.1
    tailon_port: 8080
    tailon_relative_root: /cron-logs/live/
    tailon_files:
      - "/var/www/html/cron-logs/**/*_current.log"
  - role: ara
    ara_venv_path: "{{ ansible_runner_virtualenv }}"
  - role: uwsgi
    uwsgi_apt_plugins:
      - uwsgi-plugin-python
    uwsgi_vassals:
      - name: ara
        state: present
        config:
          uid: www-data
          gid: www-data
          wsgi-file: "/var/www/ara/ara-wsgi"
          virtualenv: "{{ ansible_runner_virtualenv }}"
          plugin: python
          socket: localhost:3311
          lazy-apps: true
  - role: apache
    apache_apt_install:
      - libapache2-mod-proxy-uwsgi
    apache_mods_enabled:
      - proxy.conf
      - proxy.load
      - proxy_http.load
      - proxy_uwsgi.load
    apache_vhosts:
      - name: bastion
        document_root: /var/www/html/
        document_root_options: +FollowSymLinks
        vhost_extra: |
          AddType text/plain .log

          Redirect permanent /ara /ara/
          Redirect permanent /cron-logs/live /cron-logs/live/

          ProxyPass "/cron-logs/live/" http://localhost:{{ tailon_port }}/cron-logs/live/
          ProxyPass "/ara/" uwsgi://localhost:3311/

          SetEnv ANSIBLE_CONFIG /var/www/ara/ansible.cfg

          <Directory /var/www/ara>
            Require all granted
          </Directory>

      - name: tailon
        delete: yes
      - name: ara
        delete: yes
