dependencies:
  - role: nginx
    nginx_sites:
      - name: letsencrypt
        state: present
        port: 80
        content: |
          location /.well-known/acme-challenge {
            allow all;
            root {{ letsencrypt_webroot }}/.well-known/acme-challenge;
          }

          {% if letsencrypt_configure_redirect %}
          location / {
              return 301 https://$host$request_uri;
          }
          {% endif %}

  - role: letsencrypt
    letsencrypt_reload_handler: Reload nginx
