- name: Add sudo group
  group: name=sudo
  when: "{{ bastion_sudo_users }}"

- name: Ensure /etc/sudoers.d/ is included in /etc/sudoers
  lineinfile: dest=/etc/sudoers line='#includedir /etc/sudoers.d' state=present validate='visudo -cf %s'
  when: "{{ bastion_users }}"

- name: Ensure sudo group has NOPASSWD sudo privileges
  lineinfile: "dest=/etc/sudoers regexp='^%sudo' line='%sudo  ALL=(ALL:ALL) NOPASSWD:ALL' validate='visudo -cf %s'"
  when: "{{ bastion_sudo_users }}"

- name: Add bastion_sudo_users to sudo group
  user: name={{ item }} groups=sudo shell=/bin/bash
  with_items: "{{ bastion_sudo_users }}"

- name: Remove bastion_remove_users
  user: name={{ item }} state=absent
  with_items: "{{ bastion_remove_users }}"

- name: Add .ssh
  file: state=directory path=~{{ item }}/.ssh owner={{ item }} group={{ item }} mode=0700
  with_items: "{{ bastion_users }}"

- name: Add SSH key
  copy: src={{ item }}.authorized_keys dest=~{{ item }}/.ssh/authorized_keys owner={{ item }} group={{ item }} mode=0664
  with_items: "{{ bastion_users }}"

- name: Make sure everyone is in AllowUsers
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^AllowUsers"
    state: absent
  notify: restart sshd

- name: install required ubuntu packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libffi-dev
    - libssl-dev
    - python-dev

- name: install required python packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - shade
