---
- name: Ensure clouds.yaml group exists
  group:
    name: "{{ clouds_yaml_group }}"
    state: present

- name: Ensure clouds.yaml owner exists and is a member of the group
  user:
    name: "{{ clouds_yaml_owner }}"
    groups: "{{ clouds_yaml_group }}"
    append: true
    state: present

- name: Ensure clouds.yaml directory
  file:
    path: "{{ clouds_yaml_path | dirname }}"
    state: directory
    owner: "{{ clouds_yaml_owner }}"

- name: Write clouds.yaml
  template:
    src: clouds.yaml
    dest:  "{{ clouds_yaml_path }}"
    owner: "{{ clouds_yaml_owner }}"
    group: "{{ clouds_yaml_group }}"
    mode: "{{ clouds_yaml_mode }}"
