---
language: python
python: "2.7"
cache: pip

sudo: required
services:
  - docker

matrix:
  fast_finish: true

env:
  - TEST_RUN="ansible-playbook -i inventory/allinone-bastion bastion.yml -c docker -vv -e @secrets.yml.example --skip-tags monitoring,not-on-docker,letsencrypt"
  - TEST_RUN="ansible-playbook -i inventory/allinone install-ci.yml tests/files/validate-ci.yml -c docker -vv -e @secrets.yml.example --skip-tags monitoring,not-on-docker,letsencrypt"

before_install:
- docker pull ubuntu:xenial
- docker run -d --name allinone --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro ubuntu:xenial systemd
- docker exec -i allinone apt-get update
- docker exec -i allinone apt-get install -y python-apt ca-certificates apt-transport-https sudo ssh
- docker exec -i allinone touch /var/log/auth.log  # fail2ban fails to start without this file in place

install:
  - pip install ansible
  - pip install -r requirements.txt

script: "$TEST_RUN"

after_failure:
  - docker exec -i allinone journalctl -xe
  - docker exec -i allinone ps aux | grep zuul
  - docker exec -i allinone journalctl -u zuul-server
  - docker exec -i allinone cat /var/log/zuul/zuul-server.log
  - docker exec -i allinone cat /var/log/zuul/zuul-server-debug.log
  - docker exec -i allinone journalctl -u zuul-launcher
  - docker exec -i allinone cat /var/log/zuul/zuul-launcher-debug.log
  - docker exec -i allinone systemctl status zuul-server
  - docker exec -i allinone journalctl --since -5min
