- name: Configure bastion
  hosts: bastion
  become: true
  pre_tasks:
    - file:
        path: /root/.ssh
        state: directory
        owner: root
        mode: 0700

  roles:
    - common
    - role: dd-agent
      tags:
        - monitoring
      when: secrets is defined
    - bastion
    - role: ansible-runner
      ansible_runner_minute: "*/15"
