- name: Configure bastion
  hosts: bastion
  become: true
  roles:
    - common
    - dd-agent
    - bastion
    - role: ansible-runner
      ansible_runner_job: system-ansible
      ansible_playbook: bastion.yml
      ansible_inventory: /etc/ansible/hosts
      ansible_runner_user: root
      ansible_runner_repo: https://github.com/BonnyCI/hoist.git
      ansible_runner_minute: "*/15"
    - role: ansible-runner
      ansible_playbook: install-ci.yml
      ansible_inventory: /opt/openstack-inventory.py
      ansible_runner_job: cideploy
      ansible_runner_user: cideploy
      ansible_remote_user: ubuntu
      ansible_runner_repo: https://github.com/BonnyCI/hoist.git
      ansible_runner_minute: "*/15"
