- name: Configure bastion
  hosts: bastion
  become: true
  roles:
    - common
    - dd-agent
    - bastion
    - role: cron-ansible
      ansible_root: /opt/source/hoist
      ansible_playbook: bastion.yml
      ansible_inventory: /opt/source/hoist/inventory/bastion-localhost
      ansible_runner_user: root
    - role: cron-cideploy
      ansible_playbook: install-ci.yml
      ansible_root: /home/cideploy/hoist
      ansible_inventory: /opt/openstack-inventory.py
      ansible_runner_user: cideploy
      ansible_remote_user: ubuntu
