- name: Configure bastion
  hosts: bastion
  become: true
  pre_tasks:
    - file:
        path: /root/.ssh
        state: directory
        owner: root
        mode: 0700

  roles:
    - role: common
      common_hostname: "{{ bonnyci_hostname | default('') }}"

    - role: dd-agent
      tags:
        - monitoring
      when: secrets is defined

    - role: letsencrypt
      tags:
        - letsencrypt
      when: letsencrypt_csr_cn | default(False)
    - bastion
    - role: datadog-builder
      datadog_builder_secrets:
        api_key: "{{ secrets.datadog.api_key }}"
        app_key: "{{ secrets.datadog.ansible_app_key }}"
      when: secrets is defined
    - role: logrotate
      logrotate_configs:
        - name: datadog-builder
          path: /var/log/datadog-builder/*log
          options:
            - compress
            - missingok
            - rotate 30
            - daily
            - notifempty
      when: secrets is defined

    - role: bonnyci-test-suite

    - role: ansible-runner
      ara_enabled: true
      ara_db_username: "{{ secrets.ara.username }}"
      ara_db_password: "{{ secrets.ara.password }}"
      ara_db_host: "{{ bonnyci_ara_db_host }}"
      when: secrets is defined

    - role: tailon
      tailon_ip: 127.0.0.1
      tailon_port: 8080
      tailon_relative_root: /cron-logs/live/
      tailon_files:
        - "/var/www/html/cron-logs/**/*_current.log"

    - role: apache
      apache_mods_enabled:
        - proxy.conf
        - proxy.load
        - proxy_http.load
      apache_vhosts:
        - name: bastion
          document_root: /var/www/html/
          document_root_options: +FollowSymLinks
          ssl: "{{ bonnyci_bastion_ssl | default(False) }}"
          certificate_file: "{{ letsencrypt_cert_path | default('') }}"
          certificate_key_file: "{{ letsencrypt_key_path | default('') }}"
          certificate_chain_file: "{{ letsencrypt_chain_path | default('') }}"
          vhost_extra: |
            AddType text/plain .log

            Redirect permanent /cron-logs/live /cron-logs/live/

            ProxyPass "/cron-logs/live/" http://localhost:8080/cron-logs/live/
        - name: tailon
          delete: yes
        - name: ara
          delete: yes

    - role: filebeat
      filebeat_prospectors:
        - name: apache
          prospectors:
            - input_type: log
              document_type: apache
              paths:
                - /var/log/apache/*.log

    - role: fail2ban  # This should be last
