- name: Configure bastion
  hosts: bastion
  become: true
  pre_tasks:
    - file:
        path: /root/.ssh
        state: directory
        owner: root
        mode: 0700

  roles:
    - common
    - role: dd-agent
      tags:
        - monitoring
      when: secrets is defined
    - bastion
    - role: ansible-runner
      ansible_runner_job: system-ansible
      ansible_playbook: bastion.yml
      ansible_inventory: "/opt/source/system-ansible/inventory/{{ ci_inventory }}"
      ansible_runner_user: root
      ansible_runner_repo: "{{ hoist_repo }}"
      ansible_runner_minute: "*/15"
    - role: ansible-runner
      ansible_playbook: install-ci.yml
      ansible_inventory: "/opt/source/cideploy/inventory/{{ ci_inventory }}"
      ansible_runner_job: cideploy
      ansible_runner_user: cideploy
      ansible_remote_user: ubuntu
      ansible_runner_repo: "{{ hoist_repo }}"
      ansible_runner_minute: "*/15"
