- name: Configure bastion
  hosts: bastion
  become: true
  roles:
    - bastion
    - common
    - seed-ci
    - role: cron-ansible
      ansible_root: /opt/source/SeedCI
      ansible_playbook: bastion.yml
      ansible_inventory: /etc/ansible/hosts
      ansible_runner_user: root
    - role: cron-cideploy
      ansible_root: /opt/source/cideploy_SeedCI
      ansible_playbook: site.yml
      ansible_inventory: /opt/openstack-inventory.py
      ansible_runner_user: cideploy
