- name: Configure bastion
  hosts: bastion
  become: true
  pre_tasks:
    - file:
        path: /root/.ssh
        state: directory
        owner: root
        mode: 0700

  roles:
    - common
    - role: dd-agent
      tags:
        - monitoring
      when: secrets is defined
    - bastion
    - role: datadog-builder
      datadog_builder_secrets:
        api_key: "{{ secrets.datadog.api_key }}"
        app_key: "{{ secrets.datadog.ansible_app_key }}"
      when: secrets is defined
    - role: logrotate
      logrotate_configs:
        - name: datadog-builder
          path: /var/log/datadog-builder/*log
          options:
            - compress
            - missingok
            - rotate 30
            - daily
            - notifempty
      when: secrets is defined
    - role: ansible-runner
      ansible_runner_minute: "*/15"
