- name: Configure bastion
  hosts: bastion
  become: true
  roles:
    - common
    - role: dd-agent
      tags:
        - monitoring
      when: secrets is defined
    - bastion
    - role: ansible-runner
      ansible_runner_job: system-ansible
      ansible_playbook: bastion.yml
      ansible_inventory: /opt/source/system-ansible/inventory/bastion-localhost
      ansible_runner_user: root
      ansible_runner_repo: "git@github.ibm.com:OpenStackInnovation/hoist.git"
      ansible_runner_minute: "*/15"
    - role: ansible-runner
      ansible_playbook: install-ci.yml
      ansible_inventory: /opt/source/cideploy/inventory/ci
      ansible_runner_job: cideploy
      ansible_runner_user: cideploy
      ansible_remote_user: ubuntu
      ansible_runner_repo: "git@github.ibm.com:OpenStackInnovation/hoist.git"
      ansible_runner_minute: "*/15"
