---
- name: Create hosts and resources
  hosts: bastion
  become: true
  roles:
    - role: create-hosts
      tags: ['create-hosts']
      os_cloud: contra-sjc
      dns_subdomain: bonnyci-internal.portbleu.com
      security_groups:
        - name: ssh
          rules:
            - protocol: tcp
              port_range_min: 22
              port_range_max: 22

        - name: http
          rules:
            - protocol: tcp
              port_range_min: 80
              port_range_max: 80

        - name: https
          rules:
            - protocol: tcp
              port_range_min: 443
              port_range_max: 443

        - name: logstash
          rules:
            - protocol: tcp
              port_range_min: 5044
              port_range_max: 5044

      keys:
        - name: root-contrasjc-bastion
          public_key_file: /root/.ssh/id_rsa.pub
        - name: ci-deploy-contrasjc-bastion
          public_key_file: /home/cideploy/.ssh/id_rsa.pub

      servers:
        - name: zuul
          public_address: 169.45.113.36
          security_groups:
            - https
        - name: nodepool
        - name: logs
          public_address: 169.45.113.51
          security_groups:
            - ssh
            - http
            - https
            - logstash
