- name: Create resources
  hosts: bastion
  become: true
  tasks:
    - name: create keys
      os_keypair:
        cloud: "{{ os_cloud }}"
        state: present
        name: "{{ item.name }}"
        public_key_file: "{{ item.public_key_file }}"
      with_items: "{{ keys }}"

    - name: create servers
      os_server:
        cloud: "{{ os_cloud }}"
        name: "{{ item.name }}.bonnyci-internal.portbleu.com"
        state: present
        region_name: RegionOne
        security_groups: default
        flavor: m1.medium
        image: "{{ item.image | default('ubuntu-16.04-py27') }}"
        auto_ip: yes
        key_name: "{{ item.key_name | default('ci-deploy-contrasjc-bastion') }}"
        nics: "{{ item.nics | default([{'net-name': 'sl-private-network-01'}]) }}"
        wait: yes
      register: openstack_instances
      with_items: "{{ servers }}"

    - name: wait for new hosts to respond to ssh
      wait_for:
        port: 22
        host: "{{ item.openstack.public_v4 }}"
        search_regex: OpenSSH
      with_items: "{{ openstack_instances.results }}"

    - name: ensure new servers are in known_hosts
      lineinfile:
        dest: /home/cideploy/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + item.openstack.public_v4) }}"
      with_items: "{{ openstack_instances.results }}"
  vars:
    os_cloud: contra-sjc

    keys:
      - name: root-contrasjc-bastion
        public_key_file: /root/.ssh/id_rsa.pub
      - name: ci-deploy-contrasjc-bastion
        public_key_file: /home/cideploy/.ssh/id_rsa.pub

    servers:
      - name: zuul
      - name: nodepool
