---
- name: Common task for all nodes
  hosts: all
  become: yes
  tags: ['common']
  roles:
    - role: common
    - role: dd-agent
      tags:
        - monitoring

- name: Install mysql
  hosts: mysql
  become: yes
  tags: ['mysql']
  roles:
    - role: mysql
    - role: dd-mysql
      dd_mysql_password: "{{ secrets.datadog.mysql_password }}"
      tags:
        - monitoring
    - role: databases

- name: Install zuul
  hosts: zuul
  become: yes
  tags: ['zuul']
  roles:
    - role: dd-gearman
      tags:
        - monitoring
    - role: zuul
    - role: dd-zuul
      tags:
        - monitoring

- name: Install nodepool
  hosts: nodepool
  become: yes
  tags: ['nodepool']
  roles:
    - role: nodepool
      nodepool_statsd_enable: yes
      nodepool_mysql_user: "{{ secrets.nodepool.db_user }}"
      nodepool_mysql_password: "{{ secrets.nodepool.db_password }}"

- name: Install logging
  hosts: log
  become: yes
  tags: ['logs']
  roles:
    - role: apache
      apache_vhosts:
        - name: logs
          server_name: logs.bonnyci.com
          document_root: /var/www/bonny-logs
          document_root_allow_override: None
          document_root_mode: "0755"
          document_root_options: "+Indexes +FollowSymLinks"
