---
- name: Common task for all nodes
  hosts: all
  become: yes
  tags: ['common']
  roles:
    - role: common
    - role: dd-agent
      tags:
        - monitoring

- name: Install mysql
  hosts: mysql
  become: yes
  tags: ['mysql']
  roles:
    - role: mysql
    - role: dd-mysql
      dd_mysql_password: "{{ secrets.datadog.mysql_password }}"
      tags:
        - monitoring
    - role: databases

- name: Install zuul
  hosts: zuul
  become: yes
  tags: ['zuul']
  roles:
    - role: dd-gearman
      tags:
        - monitoring
    - role: zuul
    - role: dd-zuul
      tags:
        - monitoring
    - role: apache
      apache_vhosts:
        - name: git
          server_name: zuul.bonnyci.portbleu.com
          vhost_extra: |
            <LocationMatch "^/p/">
               Require all granted
            </LocationMatch>

            SetEnv GIT_PROJECT_ROOT /var/lib/zuul/git
            SetEnv GIT_HTTP_EXPORT_ALL 1

            AliasMatch ^/p/(.*/objects/[0-9a-f]{2}/[0-9a-f]{38})$ /var/lib/zuul/git/$1
            AliasMatch ^/p/(.*/objects/pack/pack-[0-9a-f]{40}.(pack|idx))$ /var/lib/zuul/git/$1
            ScriptAlias /p/ /usr/lib/git-core/git-http-backend/
    - role: dd-apache
      tags:
        - monitoring

- name: Install nodepool
  hosts: nodepool
  become: yes
  tags: ['nodepool']
  roles:
    - role: nodepool
      nodepool_statsd_enable: yes
      nodepool_mysql_user: "{{ secrets.nodepool.db_user }}"
      nodepool_mysql_password: "{{ secrets.nodepool.db_password }}"

- name: Install logging
  hosts: log
  become: yes
  tags: ['logs']
  roles:
    - role: apache
      apache_vhosts:
        - name: logs
          server_name: logs.bonnyci.com
          document_root: /var/www/bonny-logs
          document_root_allow_override: None
          document_root_mode: "0755"
          document_root_options: "+Indexes +FollowSymLinks"
          vhost_extra: |
            AddType text/plain .log
            AddType text/plain .sh
            AddType text/plain .yml
            AddType text/plain .yaml

    - role: dd-apache
      tags:
        - monitoring
