---
- name: Common task for all nodes
  hosts: all
  become: yes
  tags: ['common']
  roles:
    - role: admin-user
      when: bonnyci_lockdown_ssh | default(False)

    - role: common

    - role: dd-agent
      tags:
        - monitoring

    - role: letsencrypt
      tags:
        - letsencrypt
      when:
        - letsencrypt_csr_cn | default(False)

- name: Install ELK
  hosts: monitoring
  become: yes
  tags: ['elk']
  roles:
    - role: elasticsearch
      tags: ['elasticsearch']
      elasticsearch_index_settings:
        number_of_replicas: 0

    - role: dd-elasticsearch
      tags:
        - monitoring

    - role: logstash
      tags: ['logstash']
    - role: kibana
      tags: ['kibana']

- name: Install mysql
  hosts: mysql
  become: yes
  tags: ['mysql']
  roles:
    - role: mysql
    - role: dd-mysql
      dd_mysql_password: "{{ secrets.datadog.mysql_password }}"
      tags:
        - monitoring
    - role: databases

- name: Install zookeeper
  hosts: zookeeper
  become: yes
  tags: ['zookeeper']
  roles:
    - role: zookeeper
    - role: dd-zookeeper
      tags:
        - monitoring

- name: Install zuul server and launcher
  hosts: zuul
  become: yes
  tags:
    - zuul
    - zuul-server
    - zuul-launcher
  roles:
    - role: dd-gearman
      tags:
        - monitoring

    - role: zuul

    - role: dd-zuul
      tags:
        - monitoring

    - role: apache
      apache_mods_enabled: "{{ bonnyci_zuul_webapp_apache_mods_enabled }}"
      apache_vhosts: "{{ bonnyci_zuul_webapp_apache_vhosts }}"

    - role: dd-apache
      tags:
        - monitoring

    - role: logrotate
      logrotate_configs:
        - name: zuul
          path: /var/log/zuul/*log
          options:
            - compress
            - missingok
            - rotate 30
            - daily
            - notifempty

    - role: filebeat
      filebeat_prospectors:
        - name: zuul-server
          prospectors:
            - input_type: log
              document_type: python-logging
              tags:
                - zuul
                - zuul-launcher
                - zuul-server
              paths:
                - /var/log/zuul/launcher.log
                - /var/log/zuul/server.log
              multiline:
                match: after
                negate: true
                pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'

- name: Install zuul mergers
  hosts: mergers
  become: yes
  tags:
    - zuul
    - zuul-merger
  roles:
    - role: zuul
      zuul_merger_git_dir: "{{ bonnyci_zuul_merger_git_dir }}"

    - role: apache
      apache_mods_enabled: "{{ bonnyci_zuul_merger_apache_mods_enabled }}"
      apache_vhosts: "{{ bonnyci_zuul_merger_apache_vhosts }}"

    - role: dd-apache
      tags:
        - monitoring

    - role: logrotate
      logrotate_configs:
        - name: zuul
          path: /var/log/zuul/*log
          options:
            - compress
            - missingok
            - rotate 30
            - daily
            - notifempty

    - role: filebeat
      filebeat_prospectors:
        - name: zuul-merger
          prospectors:
            - input_type: log
              document_type: python-logging
              tags:
                - zuul
                - zuul-merger
              paths:
                - /var/log/zuul/merger.log
              multiline:
                match: after
                negate: true
                pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'

- name: Install nodepool
  hosts: nodepool
  become: yes
  tags: ['nodepool']
  roles:
    - role: nodepool
      nodepool_mysql_user: "{{ secrets.nodepool.db_user }}"
      nodepool_mysql_password: "{{ secrets.nodepool.db_password }}"

    - role: dd-nodepool
      tags:
        - monitoring

    - role: logrotate
      logrotate_configs:
        - name: nodepool
          path: /var/log/nodepool/*log
          options:
            - compress
            - missingok
            - rotate 10
            - size 50M
            - daily
            - notifempty

    - role: filebeat
      filebeat_prospectors:
        - name: nodepool
          prospectors:
            - input_type: log
              document_type: python-logging
              tags:
                - nodepool
              paths:
                - /var/log/nodepool/nodepool-builder.log
                - /var/log/nodepool/nodepool-deleter.log
                - /var/log/nodepool/nodepool-launcher.log
                - /var/log/nodepool/nodepoold.log
              multiline:
                match: after
                negate: true
                pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'

- name: Install logging
  hosts: log
  become: yes
  tags: ['logs']
  roles:
    - role: scp-log-receiver
      scp_log_receiver_user: "{{ bonnyci_logs_scp_user }}"
      scp_log_receiver_path:  "{{ bonnyci_logs_root_dir }}/logs"
      scp_log_receiver_authorized_key: "{{ secrets.ssh_keys.zuul.public | default(omit) }}"

    - role: os-loganalyze
      os_loganalyze_root_dir: "{{ bonnyci_logs_root_dir }}/logs"
      os_loganalyze_file_conditions: "{{ bonnyci_logs_loganalyze_file_conditions }}"

    - role: apache
      apache_apt_install: "{{ bonnyci_logs_apache_apt_install }}"
      apache_mods_enabled: "{{ bonnyci_logs_apache_mods_install }}"
      apache_vhosts: "{{ bonnyci_logs_apache_vhosts }}"

    - role: dd-apache
      tags:
        - monitoring
