---
- name: Common task for all nodes
  hosts: all
  become: yes
  tags: ['common']
  roles:
    - role: common
    - role: dd-agent
      tags:
        - monitoring

- name: Install mysql
  hosts: mysql
  become: yes
  tags: ['mysql']
  roles:
    - role: mysql
    - role: dd-mysql
      dd_mysql_password: "{{ secrets.datadog.mysql_password }}"
      tags:
        - monitoring
    - role: databases

- name: Install zookeeper
  hosts: zookeeper
  become: yes
  tags: ['zookeeper']
  roles:
    - role: zookeeper
    - role: dd-zookeeper
      tags:
        - monitoring

- name: Install zuul
  hosts: zuul
  become: yes
  tags: ['zuul']
  roles:
    - role: dd-gearman
      tags:
        - monitoring

    - role: zuul
      zuul_merger_git_dir: "{{ bonnyci_zuul_merger_git_dir }}"

    - role: dd-zuul
      tags:
        - monitoring

    - role: apache
      apache_mods_enabled: "{{ bonnyci_zuul_apache_mods_enabled }}"
      apache_vhosts: "{{ bonnyci_zuul_apache_vhosts }}"

    - role: dd-apache
      tags:
        - monitoring
    - role: geerlingguy.filebeat
      filebeat_prospectors:
        - input_type: log
          paths:
            - /var/log/zuul/gearman.log
            - /var/log/zuul/launcher.log
            - /var/log/zuul/merger.log
            - /var/log/zuul/server.log

- name: Install nodepool
  hosts: nodepool
  become: yes
  tags: ['nodepool']
  roles:
    - role: nodepool
      nodepool_mysql_user: "{{ secrets.nodepool.db_user }}"
      nodepool_mysql_password: "{{ secrets.nodepool.db_password }}"
    - role: dd-nodepool
      tags:
        - monitoring
    - role: geerlingguy.filebeat
      filebeat_prospectors:
        - input_type: log
          paths:
            - /var/log/nodepool/nodepool-builder.log
            - /var/log/nodepool/nodepool-deleter.log
            - /var/log/nodepool/nodepool-launcher.log
            - /var/log/nodepool/nodepoold.log

- name: Serve test-output logs
  hosts: log
  become: yes
  tags: ['logs']
  roles:
    - role: os-loganalyze
      os_loganalyze_root_dir: "{{ bonnyci_logs_root_dir }}"
      os_loganalyze_file_conditions: "{{ bonnyci_logs_loganalyze_file_conditions }}"

    - role: apache
      apache_apt_install: "{{ bonnyci_logs_apache_apt_install }}"
      apache_mods_enabled: "{{ bonnyci_logs_apache_mods_install }}"
      apache_vhosts: "{{ bonnyci_logs_apache_vhosts }}"

    - role: dd-apache
      tags:
        - monitoring

- name: Serve system logs
  hosts: monitor
  become: yes
  tags: ['logs']
  roles:
    - role: monitor-system-logs
