---
- name: Common task for all nodes
  hosts: nodepool.portbleu.com,zuul.portbleu.com,merger01.portbleu.com
  become: yes
  tags: ['common']
  roles:
    - role: common

- name: Install mysql
  hosts: zuul.portbleu.com
  become: yes
  tags: ['mysql']
  roles:
    - role: mysql
    - role: databases

- name: Install zuul
  hosts: zuul.portbleu.com
  tags: ['zuul']
  roles:
    - role: zuul

- name: Install nodepool
  hosts: nodepool.portbleu.com
  tags: ['nodepool']
  roles:
    - role: nodepool
