---
- name: Common task for all nodes
  hosts: nodepool.portbleu.com,zuul.portbleu.com,merger01.portbleu.com
  become: yes
  tags: ['common']
  roles:
    - role: common
    - role: dd-agent
      tags:
        - monitoring

- name: Install mysql
  hosts: zuul.portbleu.com
  become: yes
  tags: ['mysql']
  roles:
    - role: mysql
    - role: dd-mysql
      tags:
        - monitoring
    - role: databases

- name: Install zuul
  hosts: zuul.portbleu.com
  become: yes
  tags: ['zuul']
  roles:
    - role: gearman
    - role: dd-gearman
      tags:
        - monitoring
    - role: zuul
      zuul_gearman_server_start: false
    - role: dd-zuul
      tags:
        - monitoring

- name: Install nodepool
  hosts: nodepool.portbleu.com
  become: yes
  tags: ['nodepool']
  roles:
    - role: nodepool
      nodepool_providers:
        - cicloud
