- name: Provision bastions
  hosts: localhost
  tasks:
    - os_server:
        name: contrasjc-bastion
        flavor: m1.medium
        image: 7a8169b8-96d4-48ab-a607-34f79dea4156 # Ubuntu 14.04
        key_name: default
        security_groups: default
        network: internal
        cloud: contra-sjc
        floating_ips:
          - 169.45.113.62
    - os_server:
        name: hdcltl-bastion
        flavor: 2cpus-4GBram-40GBdisk
        image: 471cc7b4-648a-4008-921e-ccdc881efdec # Ubuntu 14.04
        key_name: default
        security_groups: default
        network: ibmcloud_network
        cloud: hdcltl
        floating_ips:
          - 9.70.213.207
      when: false # This is currently broken
