---
# Quartermaster installer playbook
# 
# Install with 'ansible-playbook quartermaster.yml -e @/etc/secrets.yml'
#
# Should be run on the host you want to install on (localhost)
- name: Install quartermaster
  hosts: bot
  become: true
  tags: ['common']
  roles:
    - role: admin-user
      when: bonnyci_lockdown_ssh | default(False)

    - role: common
    - role: quartermaster
      quartermaster_default_channel: "#BonnyCI"
      quartermaster_name: "quartermaster"

