- src: mbasanta.pip
  name: pip

- src: https://git.openstack.org/openstack/ansible-role-nodepool
  scm: git
  version: master

- src: https://git.openstack.org/openstack/ansible-role-zuul
  scm: git
  version: master
