---
- name: Restart zuul services
  hosts: zuul
  become: yes
  tags:
    - zuul
    - zuul-server
    - zuul-launcher
  tasks:
    - name: restart zuul-server
      service:
        name: zuul-server
        state: restarted

    - name: wait for zuul to start (check for gearman)
      wait_for:
        port: "{{ zuul_gearman_port | default(4730) }}"
        timeout: 300
        delay: 2

    - name: restart zuul-launcher
      service:
        name: zuul-launcher
        state: restarted

- name: Restart zuul mergers
  hosts: mergers
  become: yes
  tags:
    - zuul
    - zuul-merger
  tasks:
    - name: restart zuul-merger
      service:
        name: zuul-merger
        state: restarted
      with_items:
        - zuul-merger

- name: Restart nodepool services
  hosts: nodepool
  become: yes
  tags:
    - nodepool
  tasks:
    - name: Restart nodepoold
      service:
        name: nodepoold
        state: restarted

    - name: Restart other nodepool services
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - nodepool-builder
        - nodepool-deleter
        - nodepool-launcher

- name: Purge old nodepool nodes
  hosts: nodepool
  become: yes
  become_user: nodepool
  tags:
    - nodepool
  tasks:
    - name: Get nodepool nodes
      shell: '/opt/venvs/nodepool/bin/nodepool list | grep -v used | cut -d\| -f2 | grep -v + | tail -n +2'
      register: nodepool_id_list

    - name: Delete old nodepool nodes
      shell: '/opt/venvs/nodepool/bin/nodepool delete {{ item }}'
      with_items: "{{ nodepool_id_list.stdout_lines }}"
