# Softlayer machines come with SSH root access and no users set up. This doesn't
# match how OpenStack and other providers work so create a user with the right
# ssh key so we don't nee to modify our whole hoist repo to handle softlayer.
---
- hosts: all
  vars:
    softlayer_user: ubuntu
    softlayer_authorized_key: "{{ secrets.ssh_keys.cideploy.public | mandatory }}"
  tasks:
    - name: create a group
      group:
        name: "{{ softlayer_user }}"

    - name: create a user
      user:
        name: "{{ softlayer_user }}"
        group: "{{ softlayer_user }}"
        state: present

    - name: add cideploy authorized key
      authorized_key:
        user: "{{ softlayer_user }}"
        exclusive: yes
        key: "{{ softlayer_authorized_key }}"
