# Softlayer machines come with SSH root access and no users set up. This doesn't
# match how OpenStack and other providers work so create a user with the right
# ssh key so we don't nee to modify our whole hoist repo to handle softlayer.
---
- hosts: all
  vars:
    softlayer_user: ubuntu
    softlayer_authorized_key: "{{ secrets.ssh_keys.cideploy.public | mandatory }}"
  tasks:
    - name: install sudo
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - sudo

    - name: create a group
      group:
        name: "{{ softlayer_user }}"

    - name: create a user
      user:
        name: "{{ softlayer_user }}"
        group: "{{ softlayer_user }}"
        state: present

    - name: add cideploy authorized key
      authorized_key:
        user: "{{ softlayer_user }}"
        exclusive: yes
        key: "{{ softlayer_authorized_key }}"

    - name: add sudo for user
      template:
        src: user-sudoers.j2
        dest: /etc/sudoers.d/softlayer
        mode: "0440"
        owner: root
        group: root
        validate: '/usr/sbin/visudo -cf %s'
