---
- name: Common task for all nodes
  hosts: all
  become: yes
  vars:
    pip_install_method: installer
  roles:
    - role: common

- name: Install zuul
  hosts: zuul
  roles:
    - zuul

- name: Install zuul
  hosts: nodepool
  roles:
    - nodepool
