---
- name: Common task for all nodes
  hosts: all
  become: yes
  tags: ['common']
  roles:
    - role: common

- name: Install mysql
  hosts: mysql
  become: yes
  tags: ['mysql']
  roles:
    - role: mysql
    - role: databases

- name: Install zuul
  hosts: zuul
  tags: ['zuul']
  roles:
    - role: zuul

- name: Install nodepool
  hosts: nodepool
  tags: ['nodepool']
  roles:
    - role: nodepool
