#!/bin/bash -e
# This checks for any unused jobs found in the
# jobs-list.txt file generated by check-jobs.sh

layout="roles/zuul-server/templates/etc/zuul/config/layout.yaml"
job_list="$1"
if [ ! -f "$layout" ]; then
    echo "ERROR: $layout not found"
    exit 1
fi
if [ -z "$job_list" ]; then
    echo "ERROR: Must specify a file for jobs list input"
    exit 1
fi

grep -v 'jobs' < "$job_list" | while IFS= read -r job; do
    if ! grep -q "$job" "$layout"; then
        echo "WARNING: $job found but not used"
    fi
done
