- name: Install deps
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: true
  with_items:
    - run-one
    - apache2

- name: Ensure cron log path
  file:
    state: directory
    path: /var/www/html/cron-logs/system-ansible
    mode: 0755
    owner: root
    group: www-data

- name: Install config for viewing logs
  copy:
    src: etc/apache2/sites-enabled/cron-logs.conf
    dest: /etc/apache2/sites-enabled/cron-logs.conf
  notify: reload apache

- name: Enable mime_magic
  apache2_module:
    name: mime_magic
    state: present
  notify: restart apache
- name: Install config file
  template:
    src: ansible-runner-config
    dest: /etc/default/{{ ansible_runner_config_env }}
    mode: 0600
    owner: "{{ ansible_runner_user }}"
    group: "{{ ansible_runner_user }}"

- name: Install ansible-runner.sh
  copy:
    src: usr/local/bin/ansible-runner
    dest: /usr/local/bin/ansible-runner
    mode: 0755
    owner: root
    group: root
