- name: Update apt cache
  apt:
    update_cache: yes

- name: Install deps
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - git
    - cron

- name: Create callback plugins path
  file:
    path: "{{ ansible_runner_venv_path }}/plugins/callback"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Install ansible-runner
  copy:
    src: usr/local/bin/ansible-runner
    dest: /usr/local/bin/ansible-runner
    mode: 0755
    owner: root
    group: root

- name: Ensure source dir
  file:
    path: /opt/source
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Ensure cron log live path
  file:
    state: directory
    path: /var/www/html/cron-logs/live
    mode: 0755

- include: datadog.yml
  when: datadog_enabled | default(True) | bool
  tags:
    - datadog

- include: runner.yml
  with_items: "{{ ansible_runner_tasks }}"
