- name: Update apt cache
  apt:
    update_cache: yes

- name: Install deps
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - python-dev
    - libssl-dev
    - git
    - cron

- name: Install ansible-runner
  copy:
    src: usr/local/bin/ansible-runner
    dest: /usr/local/bin/ansible-runner
    mode: 0755
    owner: root
    group: root

- name: Ensure source dir
  file:
    path: /opt/source
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Ensure cron log live path
  file:
    state: directory
    path: /var/www/html/cron-logs/live
    mode: 0755

- include: runner.yml
  with_items: "{{ ansible_runner_tasks }}"
