 ### Update apt cache, but don't mark changed
 # Works around Ansible 2.2 bug
 # TODO: Remove with Ansible 2.3
- name: Update apt cache
  apt:
    update_cache: yes
  register: apt_cache
  changed_when: False

- name: Install deps
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - python-dev
    - libssl-dev
    - run-one
    - git
    - cron

- name: Install ansible
  pip:
    virtualenv: "{{ ansible_runner_virtualenv }}"
    name: ansible

- name: Create callback plugins path
  file:
    path: "{{ ansible_runner_virtualenv }}/plugins/callback"
    state: directory
    mode: 0755
    owner: root
    group: root

- block:
  - name: Install datadog callback plugin
    get_url:
      url: "{{ datadog_callback_url }}"
      dest: "{{ ansible_runner_virtualenv }}/plugins/callback/datadog_callback.py"
      mode: 0755
      owner: root
      group: root

  - name: Install datadog callback configuration
    copy:
      dest: "{{ ansible_runner_virtualenv }}/plugins/callback/datadog_callback.yml"
      content: "api_key: {{ secrets.datadog.api_key }}"
      mode: 0644
      owner: root
      group: root

  when: datadog_enabled | default(True) | bool
  tags:
    - datadog

- name: Install config file
  template:
    src: ansible-runner-config
    dest: /etc/default/{{ ansible_runner_job }}
    mode: 0600
    owner: "{{ ansible_runner_user }}"

- name: Install ansible-runner
  copy:
    src: usr/local/bin/ansible-runner
    dest: /usr/local/bin/ansible-runner
    mode: 0755
    owner: root
    group: root

- name: Ensure source dir
  file:
    path: /opt/source
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Download source
  git:
    repo: "{{ ansible_runner_repo }}"
    dest: "/opt/source/{{ ansible_runner_job }}"
    update: true

- name: Check for playbook deps
  stat:
    path: "/opt/source/{{ ansible_runner_job }}/requirements.txt"
  register: requirements_txt

- name: Install playbook deps
  pip:
    virtualenv: "{{ ansible_runner_virtualenv }}"
    requirements: "/opt/source/{{ ansible_runner_job }}/requirements.txt"
  when: requirements_txt.stat.exists

- name: Ensure cron log path
  file:
    state: directory
    path: "/var/www/html/cron-logs/{{ ansible_runner_job }}"
    mode: 0755
    owner: "{{ ansible_runner_user }}"
    group: www-data

- include: secret-file.yml
  secret_file_type: secrets
  secret_file_path: "{{ ansible_runner_secrets_path }}"
  secret_file_user: "{{ ansible_runner_user }}"

- name: Add ansible-runner cron job
  cron:
    name: "ansible-runner deploy {{ ansible_runner_job }}"
    minute: "{{ ansible_runner_minute | default(omit) }}"
    user: "{{ ansible_runner_user }}"
    job: "/usr/local/bin/ansible-runner {{ ansible_runner_job }} -e @{{ ansible_runner_secrets_path }}"
