- name: Install deps
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: true
  with_items:
    - run-one
    - apache2

- name: Ensure cron log path
  file:
    state: directory
    path: /var/www/html/cron-logs/system-ansible
    mode: 0755
    owner: root
    group: www-data

- name: Install config for viewing logs
  copy:
    src: etc/apache2/sites-enabled/cron-logs.conf
    dest: /etc/apache2/sites-enabled/cron-logs.conf
  notify: reload apache

- name: Enable apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - mime_magic
    - proxy_http

  notify: restart apache
- name: Install config file
  template:
    src: ansible-runner-config
    dest: /etc/default/{{ ansible_runner_config_env }}
    mode: 0600
    owner: "{{ ansible_runner_user }}"
    group: "{{ ansible_runner_user }}"

- name: Install tailon log web tailer
  pip:
    virtualenv: /opt/tailon
    name: tailon

- name: Install tailon init
  copy:
    dest: /etc/systemd/system/tailon.service
    src: etc/systemd/system/tailon.service

- name: Install tailon apache config
  copy:
    src: etc/apache2/conf-enabled/tailon.conf
    dest: /etc/apache2/conf-enabled/tailon.conf

- name: Start tailon
  service:
    name: tailon
    state: started

- name: Install ansible-runner.sh
  copy:
    src: usr/local/bin/ansible-runner
    dest: /usr/local/bin/ansible-runner
    mode: 0755
    owner: root
    group: root
