 ### Update apt cache, but don't mark changed
 # Works around Ansible 2.2 bug
 # TODO: Remove with Ansible 2.3
- name: Update apt cache
  apt:
    update_cache: yes
  register: apt_cache
  changed_when: False

- name: Install deps
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - python-dev
    - libssl-dev
    - git
    - cron

- name: Install ansible
  pip:
    virtualenv: "{{ ansible_runner_virtualenv }}"
    name: ansible

- name: Create callback plugins path
  file:
    path: "{{ ansible_runner_virtualenv }}/plugins/callback"
    state: directory
    mode: 0755
    owner: root
    group: root

- block:
  - name: Install datadog callback plugin
    get_url:
      url: "{{ datadog_callback_url }}"
      dest: "{{ ansible_runner_virtualenv }}/plugins/callback/datadog_callback.py"
      mode: 0755
      owner: root
      group: root

  - name: Install datadog callback configuration
    copy:
      dest: "{{ ansible_runner_virtualenv }}/plugins/callback/datadog_callback.yml"
      content: "api_key: {{ secrets.datadog.api_key }}"
      mode: 0644
      owner: root
      group: root

  when: datadog_enabled | default(True) | bool
  tags:
    - datadog

- name: Install ansible-runner
  copy:
    src: usr/local/bin/ansible-runner
    dest: /usr/local/bin/ansible-runner
    mode: 0755
    owner: root
    group: root

- name: Ensure source dir
  file:
    path: /opt/source
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Ensure source dir
  file:
    path: /opt/source
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Ensure cron log live path
  file:
    state: directory
    path: /var/www/html/cron-logs/live
    mode: 0755

- include: runner.yml
  with_items: "{{ ansible_runner_tasks }}"
