- set_fact:
    venv_dir: "/opt/venvs/{{ item.name }}"

- name: Install ansible
  pip:
    virtualenv: "{{ venv_dir }}"
    name: ansible

- name: Create callback plugins path
  file:
    path: "{{ venv_dir }}/plugins/callback"
    state: directory
    mode: 0755
    owner: root
    group: root

- block:
  - name: Install datadog callback plugin
    get_url:
      url: "{{ datadog_callback_url }}"
      dest: "{{ venv_dir }}/plugins/callback/datadog_callback.py"
      mode: 0755
      owner: root
      group: root

  - name: Install datadog callback configuration
    copy:
      dest: "{{ venv_dir }}/plugins/callback/datadog_callback.yml"
      content: "api_key: {{ secrets.datadog.api_key }}"
      mode: 0644
      owner: root
      group: root

  when: datadog_enabled | default(True) | bool
  tags:
    - datadog

- name: Ensure virtualenv ownership
  file:
    dest: "{{ venv_dir }}"
    owner: "{{ item.user }}"
    recurse: yes

- name: Install config file
  template:
    src: ansible-runner-config
    dest: /etc/default/{{ item.name }}
    mode: 0600
    owner: "{{ item.user }}"

- name: Download source
  git:
    repo: "{{ item.repo }}"
    dest: "/opt/source/{{ item.name }}"
    update: true

- name: Ensure source ownership
  file:
    dest: "/opt/source/{{ item.name }}"
    owner: "{{ item.user }}"
    recurse: yes

- name: Check for playbook deps
  stat:
    path: "/opt/source/{{ item.name }}/requirements.txt"
  register: requirements_txt

- name: Install playbook deps
  pip:
    virtualenv: "{{ venv_dir }}"
    requirements: "/opt/source/{{ item.name }}/requirements.txt"
  when: requirements_txt.stat.exists

- include: secret-file.yml
  secret_file_type: secrets
  secret_file_path: "{{ ansible_runner_secrets_path }}"
  secret_file_user: "{{ item.user }}"

- name: Ensure cron log path
  file:
    state: directory
    path: "/var/www/html/cron-logs/{{ item.name }}"
    mode: 0755
    owner: "{{ item.user }}"
    group: www-data

- name: Add default PATH to cron file
  cron:
    name: PATH
    env: yes
    user: "{{ item.user }}"
    value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

- name: Add ansible-runner cron job
  cron:
    name: "ansible-runner deploy {{ item.name}}"
    minute: "{{ ansible_runner_minute | default(omit) }}"
    user: "{{ item.user }}"
    job: "/usr/local/bin/ansible-runner {{ item.name }} -e @{{ ansible_runner_secrets_path }}"

- include: ara.yml
  when: ara_enabled | default(False) | bool
