dependencies:
  - role: python-app
    name: zuul
    python_app_python3: "{{ zuul_zuul_v3 | bool }}"
    python_app_pipdeps:
      - name: pyzmq
        when: not zuul_zuul_v3
      - name: ansible
      - name: statsd
      - name: git+https://github.com/sigmavirus24/github3.py.git@8e9ca0056b8fed956b66dafb5398757cd8d8bed9#egg=Github3.py
        when: not zuul_zuul_v3
      - name: git+https://github.com/BonnyCI/datadog-logging.git#egg=datadog-logging
        state: latest
        when: zuul_use_datadog_logging

    python_app_git_repo: "{{ zuul_git_repo_url }}"
    python_app_git_version: "{{ zuul_git_branch }}"
