---
- name: create dirs
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
  with_items:
    - /etc/os_loganalyze/wsgi

- name: create config files
  template:
    src: "etc/os_loganalyze/{{ item }}"
    dest: "/etc/os_loganalyze/{{ item }}"
  with_items:
    - wsgi.conf
    - file_conditions.yaml
    - wsgi/os-loganalyze.py
