- job:
    name: ubuntu-hoist
    node: 'ubuntu-hoist'

    builders:
      - zuul-git-prep
      - install-ansible
      - shell: |
          source /opt/venvs/ansible/bin/activate
          ansible-playbook -i inventory/nodepool.py install-ci.yml --skip-tags monitoring -e @secrets.yml.example
          ansible-playbook -i inventory/nodepool.py  tests/validate-ci.yml

    publishers:
      - console-log
