---
- job:
    name: ubuntu-hoist
    node: 'ubuntu-hoist'

    builders:
      - node-info
      - zuul-git-prep
      - install-ansible
      - shell: |
          #!/bin/bash -ex
          source /opt/venvs/ansible/bin/activate
          ansible-playbook -i inventory/nodepool.py install-ci.yml --skip-tags monitoring -e @secrets.yml.example
          ansible-playbook -i inventory/nodepool.py tests/validate-ci.yml

    publishers:
      - console-log

- job:
    name: hoist-checks
    node: 'ubuntu-xenial'

    builders:
      - zuul-git-prep
      - shell: |
          #!/bin/bash -ex
          ./tests/test-zuul-jobs.sh job-list.txt
          python tests/layout-checks.py job-list.txt
          ./tests/shellcheck-test.sh
          ./tests/signed-off-by-test.sh

    publishers:
      - console-log
