- job:
    name: ubuntu-hoist
    node: 'ubuntu-hoist'

    builders:
      - zuul-git-prep
      - shell: |
          tmpdir=$(mktemp -d)
          trap "rm -rf $tmpdir" EXIT
          virtualenv $tmpdir/venv
          source $tmpdir/venv/bin/activate
          pip install ansible
          pip install -r requirements.txt
          ansible-playbook -i inventory/nodepool.py install-ci.yml --skip-tags monitoring -e @secrets.yml.example
          ansible-playbook -i inventory/nodepool.py  tests/validate-ci.yml

    publishers:
      - console-log
