- job:
    name: tox_py27
    node: 'ubuntu-xenial'

    builders:
      - zuul-git-prep
      - shell: |
          virtualenv venv
          source venv/bin/activate
          pip install tox
          tox -e py27

    publishers:
      - console-log
