- job:
    name: tox_py27
    node: 'ubuntu-xenial'

    builders:
      - zuul-git-prep
      - shell: |
          tmpdir=$(mktemp -d)
          trap "rm -rf $tmpdir" EXIT
          virtualenv $tmpdir/venv
          source $tmpdir/venv/bin/activate
          pip install tox
          tox -e py27,pep8

    publishers:
      - console-log
