---
- name: Create the zuul group
  group:
    name: zuul
    state: present

- name: Create zuul user
  user:
    name: zuul
    group: zuul
    home: "{{ zuul_home_dir }}"
    system: yes
    state: present

- name: Create directories
  file:
    path: "{{ item.name }}"
    state: directory
    mode: "{{ item.mode | default('0755') }}"
    owner: zuul
    group: zuul
  with_items:
    - name: "{{ zuul_config_dir }}"
    - name: "{{ zuul_log_dir }}"
    - name: "{{ zuul_secrets_dir }}"
      mode: "0700"

- name: Install zuul config
  template:
    src:  "{{ zuul_template_config }}"
    dest: "{{ zuul_config_dir }}/{{ zuul_service_name }}.conf"
    owner: zuul

- name: Install connection secrets
  copy:
    dest: "{{ zuul_secrets_dir }}/{{ item.name }}"
    src: "{{ item.src | default(omit) }}"
    content: "{{ item.content | default(omit) }}"
    mode: "{{ item.mode | default('0600') }}"
    owner: zuul
    group: zuul
  with_items: "{{ zuul_secrets }}"

- name: Install service environment configs
  template:
    src: etc/default/zuul
    dest: /etc/default/{{ zuul_service_name }}

- name: Install systemd unit files
  template:
    src: "{{ zuul_template_service }}"
    dest: /etc/systemd/system/{{ zuul_service_name }}.service
  notify:
    - Reload systemd units

- name: Install logging config
  template:
    src: "{{ zuul_template_logging }}"
    dest: "/etc/zuul/{{ zuul_service_name }}-logging.conf"
    owner: zuul

- name: Enable zuul services
  service:
    name: "{{ zuul_service_name }}"
    enabled: "{{ zuul_service_enabled | bool }}"

- name: Start zuul services
  service:
    name: "{{ zuul_service_name }}"
    state: started
  when: zuul_service_start

- name: Install any ssh known host keys
  known_hosts:
    path: "/etc/ssh/ssh_known_hosts"
    key: "{{ item.key }}"
    host: "{{ item.host }}"
  with_items: "{{ zuul_ssh_known_hosts }}"
