---
 ### Update apt cache, but don't mark changed
 # Works around Ansible 2.2 bug
 # TODO: Remove with Ansible 2.3
 - name: Update apt cache
   apt:
     update_cache: yes
   register: apt_cache
   changed_when: False
   failed_when: "apt_cache.cache_updated != True"

 - name: Install the MySQL packages
   apt:
     name: "{{ item }}"
     state: installed
   with_items:
     - mysql-server
     - mysql-client
     - python-mysqldb
     - libmysqlclient-dev

 - name: Set mysql_flavor
   set_fact: mysql_flavor=mysql

 - name: Set mysql_daemon_name
   set_fact: mysql_daemon_name=mysqld

 - name: Install mysql.conf
   template:
     src: etc/mysql/mysql.conf.d/mysqld.cnf
     dest: /etc/mysql/mysql.conf.d/mysqld.cnf
   notify: Restart MySQL

 - meta: flush_handlers

 - name: Start + enable the mysql service
   service:
     name: mysql
     state: started
     enabled: true

 - include: common.yml
