- name: Add bubblewrap PPA
  apt_repository:
    repo: "ppa:openstack-ci-core/bubblewrap"
    state: present
    update_cache: yes

- name: Install bubblewrap
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - bubblewrap

- name: Install zuul-executor logging config
  template:
    src: "etc/zuul/logging.conf"
    dest: "/etc/zuul/{{ item }}-logging.conf"
    owner: zuul
  with_items:
    - executor
  notify: Restart zuul
