- name: Install logging config
  template:
    src: "etc/zuul/launcher-logging.conf"
    dest: "/etc/zuul/launcher-logging.conf"
    owner: zuul
  notify: Restart zuul

- name: Install job definitions
  synchronize:
    src: files/jobs/
    dest: /var/lib/zuul/jobs/
    rsync_opts:
      - "--chown=zuul:zuul"
  notify: Reconfigure zuul-launcher
