- name: Install zuul-launcher logging config
  template:
    src: "etc/zuul/logging.conf"
    dest: "/etc/zuul/{{ item }}-logging.conf"
    owner: zuul
  notify: Restart zuul
  with_items:
    - launcher

- name: Install job definitions
  synchronize:
    src: files/jobs/
    dest: /var/lib/zuul/jobs/
    rsync_opts:
      - "--chown=zuul:zuul"
  notify: Reconfigure zuul-launcher
