---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - build-essential
    - git
    - python-dev
    - libssl-dev

- name: Create the zuul group
  group:
    name: zuul
    state: present

- name: Create zuul user
  user:
    name: zuul
    group: zuul
    home: /var/lib/zuul
    system: yes
    state: present

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: zuul
    group: zuul
  with_items:
    - /etc/zuul/config
    - /var/log/zuul

- name: "Create zuul's ~/.ssh"
  file:
    path: /var/lib/zuul/.ssh/
    state: directory
    owner: zuul
    group: zuul
    mode: 0700

- name: Install zuul private ssh key
  copy:
    dest: /var/lib/zuul/.ssh/id_rsa
    content: "{{ secrets.ssh_keys.zuul.private }}"
    owner: zuul
    group: zuul
    mode: 0600

- name: Install zuul public ssh key
  copy:
    dest: /var/lib/zuul/.ssh/id_rsa.pub
    content: "{{ secrets.ssh_keys.zuul.public }}"
    owner: zuul
    group: zuul
    mode: 0644

- name: Create /opt/{source, venvs}
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items:
    - /opt/source
    - "{{ zuul_venv_dir }}"

- name: Checkout zuul
  git:
    dest: /opt/source/zuul
    repo: "{{ zuul_git_repo_url }}"
    version: "{{ zuul_git_branch }}"
  register: zuul_git

- name: Install zuul
  pip:
    extra_args: -U
    name: /opt/source/zuul
    virtualenv: "{{ zuul_venv_dir }}"
  when: zuul_git.changed
  notify: Restart zuul

- name: Install missing pip dependencies
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version|default(omit) }}"
    virtualenv: "{{ zuul_venv_dir }}"
  with_items:
    - { name: 'jenkins-job-builder', version: '1.6.1' }
    - { name: 'pyzmq' }
    - { name: 'ansible' }

- name: Install statsd
  pip:
    name: "{{ item }}"
    virtualenv: "{{ zuul_venv_dir }}"
  with_items:
    - statsd
  when: zuul_statsd_enable

- name: Install zuul config
  template:
    src: etc/zuul/zuul.conf
    dest: /etc/zuul/zuul.conf
    owner: zuul
  notify: Restart zuul

- name: Install service environment configs
  template:
    src: etc/default/zuul
    dest: /etc/default/{{ item }}
  with_items: "{{ zuul_components }}"
  notify: Restart zuul

- name: Install systemd unit files
  template:
    src: etc/systemd/system/zuul.service
    dest: /etc/systemd/system/{{ item }}.service
  with_items: "{{ zuul_components }}"
  notify:
    - Reload systemd units
    - Restart zuul

- name: Configure zuul-server
  include: server.yml
  when: "'zuul-server' in zuul_components"

- name: Configure zuul-launcher
  include: launcher.yml
  when: "'zuul-launcher' in zuul_components"

- name: Configure zuul-merger
  include: merger.yml
  when: "'zuul-merger' in zuul_components"

- meta: flush_handlers

- name: Enable zuul services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ zuul_components }}"
