- name: Install logging config
  template:
    src: "etc/zuul/logging.conf"
    dest: "/etc/zuul/{{ item }}-logging.conf"
    owner: zuul
  with_items:
    - gearman
    - scheduler
  notify: Restart zuul

- name: Create zuul status lib dir
  file:
    path: /opt/source/zuul/etc/status/public_html/lib
    state: directory

- name: Install jquery and jquery-visibility
  get_url:
    url: "{{ item }}"
    dest: /opt/source/zuul/etc/status/public_html/lib
  with_items:
    - https://code.jquery.com/jquery.min.js
    - https://raw.githubusercontent.com/mathiasbynens/jquery-visibility/master/jquery-visibility.js
    - https://raw.githubusercontent.com/prestontimmons/graphitejs/master/jquery.graphite.js

- name: Create bootstrap css dir
  file:
    path: /opt/source/zuul/etc/status/public_html/lib/bootstrap/css
    state: directory

- name: Download bootstrap
  get_url:
    url: https://maxcdn.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css
    dest: /opt/source/zuul/etc/status/public_html/lib/bootstrap/css/bootstrap.min.css
