---
- name: Write logging config
  template:
    src: "etc/nodepool/logging.conf"
    dest: "/etc/nodepool/{{ item }}_logging.conf"
    owner: root
    group: nodepool
    mode: 0640
  with_items:
    - nodepool-builder
    - nodepool-deleter
    - nodepool-launcher
    - nodepoold

- name: Install systemd unit files
  template:
    src: "etc/systemd/system/{{ item }}.service"
    dest: "/etc/systemd/system/{{ item }}.service"
    owner: root
    group: root
    mode: 0644
  with_items:
    - nodepool-builder
    - nodepool-deleter
    - nodepool-launcher
    - nodepoold
  notify:
    - Reload systemd units
    - Restart nodepool

- meta: flush_handlers

- name: Enable and start systemd service
  service:
    enabled: yes
    state: running
    service: "{{ item }}"
  with_items:
    - nodepool-builder
    - nodepool-deleter
    - nodepool-launcher
    - nodepoold
