---
- name: Write logging config
  template:
    src: "etc/nodepool/logging.conf"
    dest: "/etc/nodepool/{{ item }}_logging.conf"
    owner: root
    group: nodepool
    mode: 0640
  with_items:
    - nodepool-builder
    - nodepool-launcher

- name: Install systemd unit files
  template:
    src: "etc/systemd/system/{{ item }}.service"
    dest: "/etc/systemd/system/{{ item }}.service"
    owner: root
    group: root
    mode: 0644
  with_items:
    - nodepool-builder
    - nodepool-launcher
  notify:
    - Reload systemd units
    - Restart nodepool
