---
- name: Install deps
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - cron

- name: Create source directories
  file:
    path: /etc/datadog-builder
    state: directory
    mode: 0755
    owner: root
    group: root

- name: create datadog-builder group
  group:
    name: datadog-builder
    state: present

- name: create datadog-builder user
  user:
    name: datadog-builder
    group: datadog-builder
    home: /var/lib/datadog-builder
    state: present

- name: Create log file
  file:
    path: /var/log/datadog-builder
    state: directory
    mode: 0755
    owner: datadog-builder
    group: datadog-builder

- name: Create datadog-builder secrets
  copy:
    dest: /etc/datadog-builder/datadog-secrets.yml
    content: "{{ datadog_builder_secrets | default({}) | to_nice_yaml(indent=2) }}"
    mode: 0600
    owner: datadog-builder

- name: Update monitors repo
  git:
    dest: "{{ datadog_builder_monitor_dir }}"
    repo: "{{ datadog_builder_monitor_url }}"
    update: "{{ datadog_builder_monitor_update }}"
    version: "{{ datadog_builder_monitor_branch }}"

- name: Setup cron job
  cron:
    name: datadog-builder
    user: datadog-builder
    minute: "*/15"
    job: >
      /opt/venvs/datadog-builder/bin/datadog-builder
      --config /etc/datadog-builder/datadog-secrets.yml
      update {{ datadog_builder_monitor_dir }}/{{ datadog_builder_monitor_file }}
      2>&1 >> /var/log/datadog-builder/datadog-builder.log
