#!/bin/bash

# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# dib-lint: disable=setu setpipefail
if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -e

mkdir -p $TMP_HOOKS_PATH/nodepool-scripts

if [ -n $DIB_NODEPOOL_SCRIPT_DIR ]; then
    # Copy the scripts from the nodepool script dir into the staging directory.
    pushd $DIB_NODEPOOL_SCRIPT_DIR
    cp -ar $DIB_NODEPOOL_SCRIPTS $TMP_HOOKS_PATH/nodepool-scripts/
    popd
fi
