---
dependencies:
  - role: apache
    apache_mods_enabled:
      - status.load
    apache_mods_disabled:
      - status.conf
    apache_vhosts:
      - name: status
        host: "127.0.0.1"
        listen_host: "127.0.0.1"
        port: "{{ dd_apache_status_port }}"
        global_vhost_settings: |
          ExtendedStatus On

        vhost_extra: |
          <Location /server-status>
            SetHandler server-status
            Require local
          </Location>

          <IfModule mod_proxy.c>
            ProxyStatus On
          </IfModule>

  - role: dd-checks
    datadog_checks:
      apache:
        instances:
          - apache_status_url: "{{ dd_apache_status_url }}"
            disable_ssl_validation: "{{ dd_apache_disable_ssl_validation }}"
            connect_timeout: "{{ dd_apache_connect_timeout }}"
            receive_timeout: "{{ dd_apache_receive_timeout }}"
