#!/bin/bash

# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# dib-lint: disable=setu setpipefail
if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -e

# always make the nodepool-scripts directory even if nothing goes in it
mkdir -p /opt/nodepool-scripts

# copy the scripts from the stagin directory into the image
if [ -d /tmp/in_target.d/nodepool-scripts ]; then
   cp -ar /tmp/in_target.d/nodepool-scripts/* /opt/nodepool-scripts/
fi

# set the correct folder permissions
chown -R root:root /opt/nodepool-scripts
chmod -R a+rX /opt/nodepool-scripts
