- name: Ensure cron log path
  file:
    state: directory
    path: /var/www/html/cron-logs/system-ansible
    mode: 0755
    owner: root
    group: www-data

- name: Cron system ansible
  cron:
    name: "system ansible"
    minute: "*/15"
    job: "/usr/local/bin/ansible-runner system-ansible"
