- name: Ensure source dir
  file:
    path: /opt/source
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Download hoist from github
  git:
    repo: https://github.com/BonnyCI/hoist.git
    dest: /opt/source/hoist
    update: true

- name: Ensure cron log path
  file:
    state: directory
    path: /var/www/html/cron-logs/system-ansible
    mode: 0755
    owner: root
    group: www-data

- name: Cron system ansible
  cron:
    name: "system ansible"
    minute: "*/15"
    job: "/usr/local/bin/ansible-runner system-ansible"
