---
- name: Reload systemd units
  command: systemctl daemon-reload

- name: Restart quartermaster
  service:
    name: quartermaster
    state: restarted

- name: Init database
  shell: /opt/quartermaster/quartermaster init --config /etc/quartermaster/quartermaster.yaml --loglevel debug
  args:
    executable: /bin/bash
