- name: Install bindeps for ansible pip deps
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - python-dev
    - libssl-dev
    - python-virtualenv

- name: Install ansible
  pip:
    virtualenv: /opt/ansible
    name: ansible
