- name: Install fail2ban
  when: ansible_os_family == 'Debian'
  apt:
    name: fail2ban
    state: present

- name: Install fail2ban
  when: ansible_os_family == 'RedHat'
  yum:
    name:
      - fail2ban

- name: Enable fail2ban jails
  template:
    src: etc/fail2ban/jail.d/jail.local.j2
    dest: /etc/fail2ban/jail.d/{{ item.name }}.local
  vars:
    jail: '{{ item }}'
  with_items: '{{ fail2ban_jails }}'
  notify: 'restart fail2ban'
