---
- name: Install common packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - build-essential
    - jq
    - netcat
    - net-tools

- name: Put hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1 {{ ansible_hostname }} localhost'
  tags: ['not-on-docker']

- name: Set custom bash prompt for per-environment nodes
  template:
    dest: /etc/profile.d/bash_prompt.sh
    src: etc/profile.d/bash_prompt.sh
  when: environment_name is defined
