---
- name: Install common packages
  apt:
    name: "{{ item }}"
    state: installed
  when: ansible_os_family == "Debian"
  with_items:
    - build-essential
    - jq
    - netcat
    - net-tools

- name: Install common packages
  yum:
    name:
      - make
      - automake
      - gcc
      - gcc-c++
      - kernel-devel
      - jq
  when: ansible_os_family == "RedHat"

- name: set hostname
  hostname:
    name: "{{ common_hostname }}"
  when: common_hostname | string | length > 0
  tags: ['not-on-docker']

- name: Put hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1 {{ common_hostname }} {{ ansible_hostname }} localhost'
  tags: ['not-on-docker']

- name: Set custom bash prompt for per-environment nodes
  template:
    dest: /etc/profile.d/bash_prompt.sh
    src: etc/profile.d/bash_prompt.sh
  when: environment_name is defined
