---
 ### Update apt cache, but don't mark changed
 # Works around Ansible 2.2 bug
 # TODO: Remove with Ansible 2.3
- name: Update apt cache
  apt:
    update_cache: yes
  changed_when: False

- name: Install deps
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - gcc
    - libffi-dev
    - python3-dev
    - python-dev
    - libssl-dev

- name: Create group
  group:
    name: "{{ quartermaster_group }}"
    state: present

- name: Create user
  user:
    name: "{{ quartermaster_user }}"
    group: "{{ quartermaster_group }}"
    home: "{{ quartermaster_home_dir }}"
    system: yes
    state: present

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ quartermaster_user }}"
    group: "{{ quartermaster_group }}"
  with_items:
    - "{{ quartermaster_home_dir }}"
    - "{{ quartermaster_log_dir }}"
    - "{{ quartermaster_venv_dir }}"
    - "{{ quartermaster_config_dir }}"

- block:
    ### This is hacky, but seems necessary to seed a venv w/ py3,
    #   then use that venv's pip...
  - name: Seed quartermaster py3 venv
    pip:
      name: pip
      virtualenv: "{{ quartermaster_venv_dir }}"
      virtualenv_python: "/usr/bin/python3"
  - name: Install errbot python package
    pip:
      name: errbot
      executable: "{{ quartermaster_venv_dir }}/bin/pip"
   
- name: Install errbot python deps
  pip:
    name: irc
    executable: "{{ quartermaster_venv_dir }}/bin/pip"

- name: Install quartermaster config
  template:
    src: config.py
    dest: "{{ quartermaster_config_dir }}/config.py"
    owner: quartermaster
    mode: 0600

- name: Install quartermaster init
  template:
    src: etc/systemd/system/quartermaster.service
    dest: /etc/systemd/system/quartermaster@.service
  notify: Restart quartermaster
  register: quartermaster_init_file

- name: Enable quartermaster service
  systemd:
    name: "quartermaster@{{ quartermaster_name }}"
    state: "{{ quartermaster_service_state }}"
    enabled: "{{ quartermaster_service_enabled }}"
    daemon_reload: "{{ quartermaster_init_file.changed }}"
