---
- name: Reload systemd units
  command: systemctl daemon-reload

- name: Restart nodepool
  service:
    name: "{{ item }}"
    state: restarted
  with_items: nodepool_services
    - nodepool-builder
    - nodepoold

- name: Restart nodepool builder
  service:
    name: nodepool-builder
    state: restarted
