---
- name: Reload systemd units
  command: systemctl daemon-reload

- name: Restart nodepool
  when: not nodepool_zuul_v3
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - nodepool-builder
    - nodepool-deleter
    - nodepool-launcher
    - nodepoold

- name: Restart nodepool
  when: nodepool_zuul_v3
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - nodepool-builder
    - nodepool-launcher

- name: Restart nodepool builder
  service:
    name: nodepool-builder
    state: restarted
