---
- name: Reload systemd units
  command: systemctl daemon-reload

- name: Restart nodepool
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - nodepool-builder
    - nodepool-deleter
    - nodepool-launcher
    - nodepoold

- name: Restart nodepool builder
  service:
    name: nodepool-builder
    state: restarted
