---
- name: Install elasticsearch
  when: ansible_os_family == 'Debian'
  apt:
    name: elasticsearch
    state: present

- name: Install elasticsearch
  when: ansible_os_family == 'RedHat'
  yum:
    name: elasticsearch
    state: present

- name: Configure Elasticsearch.
  template:
    src: "etc/elasticsearch/{{ item }}"
    dest: "/etc/elasticsearch/{{ item }}"
    owner: root
    group: elasticsearch
    mode: 0660
  with_items:
    - jvm.options
    - elasticsearch.yml
  notify: restart elasticsearch

- meta: flush_handlers

- name: Start Elasticsearch.
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Make sure Elasticsearch is running before proceeding.
  wait_for:
    host: "{{ elasticsearch_network_host }}"
    port: "{{ elasticsearch_http_port }}"
    delay: 3
    timeout: 300

- name: Set index-level settings
  when: elasticsearch_index_settings is defined
  uri:
    method: PUT
    url: http://localhost:9200/_template/all
    body_format: json  # This will convert yaml data to a json string
    body:
      template: '*'
      order: 0
      settings: "{{ elasticsearch_index_settings }}"
