# {{ ansible_managed }}

pipelines:
  - name: check
    manager: IndependentPipelineManager
    precedence: normal
    source: gerrit
    trigger:
      gerrit:
        - event: patchset-created
    success:
      gerrit:
        verified: 1
    failure:
     gerrit:
        verified: -1

  - name: check_github
    manager: IndependentPipelineManager
    source: github
    trigger:
      github:
        - event:
            - pr-open
            - pr-change
            - pr-reopen
    success:
      github:
        status: true
        comment: true
    failure:
      github:
        status: true
        comment: true

  - name: gate
    manager: DependentPipelineManager
    precedence: high
    source: gerrit
    trigger:
      gerrit:
        - event: comment-added
          approval:
            - workflow: 1
        - event: comment-added
          approval:
            - verified: 1
    require:
      approval:
        - workflow: 1
        - verified: 1
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 2
        submit: true
    failure:
      gerrit:
        verified: -2

jobs: []

project-templates:
  - name: noop-jobs
    check:
      - noop
    gate:
      - noop

projects:
  - name: doc
    template:
      - name: noop-jobs

  - name: BonnyCI/sandbox
    check_github:
      - noop
