# {{ ansible_managed }}

includes:
  - python-file: bonnyci_functions.py

pipelines:
  - name: check_github
    manager: IndependentPipelineManager
    source: github
    trigger:
      github:
        - event:
            - pr-open
            - pr-change
            - pr-reopen
        - event: pr-comment
          comment: (?i)recheck
    start:
      github:
        status: true
    success:
      github:
        status: true
        status_url: &log_link http://logs.bonnyci.com/{pipeline.name}/{change.project.name}/{change.number}/{item.enqueue_time}/
        comment: false
    failure:
      github:
        status: true
        status_url: *log_link
        comment: true

  - name: gate_github
    manager: DependentPipelineManager
    precedence: high
    source: github
    trigger:
      github:
        - event: pr-label
          label: 'approved'
    start:
      github:
        comment: true
        label: '-approved'
        status: true
    success:
      github:
        comment: false
        merge: true
        label: 'approved'
        status: true
        status_url: *log_link
    failure:
      github:
        comment: true
        label: '-approved'
        status: true
        status_url: *log_link

jobs:
  # every job invokes the set_node_options file in bonnyci_functions.py
  - name: ^.*$
    parameter-function: set_node_options

projects:
  - name: BonnyCI/hoist
    check_github:
      - ubuntu-hoist
      - ansible-syntax
      - hoist-checks
    gate_github:
      - echo-true

  - name: BonnyCI/sandbox
    check_github:
      - echo-true
      - noop
    gate_github:
      - echo-true
      - noop

  - name: BonnyCI/zuul
    check_github:
      - tox_py27
    gate_github:
      - tox_py27

  - name: j2sol/giftwrap
    check_github:
      - tox_py27
    gate_github:
      - tox_py27
