---
- name: Create ARA database
  become: yes
  mysql_db:
    name: ara
    state: present

- name: Create ARA user 
  mysql_user:
    name: "{{ ara_db_username }}"
    host: "%"
    password: "{{ ara_db_password }}"
    priv: "ara.*:ALL"
    state: present
