---
- name: Install deps
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - gcc
    - libffi-dev
    - python-dev
    - libssl-dev

- name: Install ara
  pip:
    name: "ara>=0.13.0"
    virtualenv: "{{ ara_venv_path }}"

- name: Install database dependencies
  pip:
    name: pymysql
    virtualenv: "{{ ara_venv_path }}"

- name: Ensure ara directories
  file:
    path: "/var/www/{{ item }}"
    state: directory
    mode: 0755
    owner: www-data
    group: www-data
  with_items:
    - ara
    - ara/.ansible

- name: Ensure ara database directory is world-writable
  file:
    path: "/var/www/ara/.ara"
    state: directory
    mode: 0777
    owner: www-data
    group: www-data

- name: Copy ARA wsgi script into place
  copy:
    src: "{{ ara_venv_path }}/bin/ara-wsgi"
    dest: /var/www/ara/
    remote_src: True


- name: Install ARA configuration
  template:
    src: var/www/ara/ansible.cfg
    dest: /var/www/ara/ansible.cfg
    mode: 0600
    owner: www-data
    group: www-data

- name: Make sure apache can read everything
  file:
    path: /var/www/ara
    owner: www-data
    group: www-data
    recurse: yes
