---
- name: Ensure ara directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ ara_file_owner }}"
    group: "{{ ara_file_group }}"
  with_items:
    - "{{ ara_webroot }}"
    - "{{ ara_webroot }}/.ansible"

- name: Ensure ara database directory is world-writable
  file:
    path: "{{ ara_webroot }}/.ara"
    state: directory
    mode: 0777
    owner: "{{ ara_file_owner }}"
    group: "{{ ara_file_group }}"

- name: Install ARA configuration
  template:
    src: var/www/ara/ansible.cfg
    dest: "{{ ara_webroot }}/ansible.cfg"
    mode: 0600
    owner: "{{ ara_file_owner }}"
    group: "{{ ara_file_group }}"

- name: Make sure apache can read everything
  file:
    path: "{{ ara_webroot }}"
    owner: "{{ ara_file_owner }}"
    group: "{{ ara_file_group }}"
    recurse: yes
