# Common file to be used across all jobs
# macros, builders, etc..

- publisher:
    name: console-log
    publishers:
      - scp:
          site: bonnyci-scp
          files:
            - target: 'logs/$LOG_PATH'
              copy-console: true
              copy-after-failure: true

# This is the base builder to get source code from the project onto the builder
# in the homedir of the user on the builder (so that all the code is available in pwd).
# This all goes away in v3 which will push the code to the builder.
# Lifted from infra project-config jenkins/jobs/macros.yaml
- builder:
    name: zuul-git-prep
    builders:
      - shell: |
          #!/bin/bash -xe
          CLONEMAP=`mktemp`
          function cleanup {
              # In cases where zuul-cloner is aborted during a git
              # clone operation, git will remove the git work tree in
              # its cleanup. The work tree in these jobs is the
              # workspace directory, which means that subsequent
              # jenkins post-build actions can not run because the
              # workspace has been removed.
              # To reduce the likelyhood of this having an impact,
              # recreate the workspace directory if needed
              mkdir -p $WORKSPACE
              rm -f $CLONEMAP
          }
          trap cleanup EXIT
          cat > $CLONEMAP << EOF
          clonemap:
            - name: $ZUUL_PROJECT
              dest: .
          EOF
          zuul-cloner https://github.com/ -m $CLONEMAP $ZUUL_PROJECT
