---
- name: datadog mysql user
  mysql_user:
    name: "{{ dd_mysql_user }}"
    host: localhost
    password: "{{ dd_mysql_password }}"
    priv: "*.*:REPLICATION CLIENT,PROCESS/performance_schema.*:SELECT"
    state: present
