- name: Install SSHD
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - openssh-server

- name: setup sshd config
  template:
    src: etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    mode: "0644"
  notify: Restart sshd

- name: ensure ssh started
  service:
    name: ssh
    state: started
    enabled: yes
