- name: setup sshd config
  template:
    src: etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    mode: "0644"
  notify: Restart sshd

- name: ensure ssh started
  service:
    name: "{{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
    state: started
    enabled: yes
